export const PLATFORMS = [
  {
    label: "GitHub",
    value: "github",
    icon: "/images/icon-github.svg",
    placeholder: "e.g. https://github.com/username",
    bgColor: "#000000",
    url: "#",
    validation: /^(https?:\/\/)?(www\.)?github\.com\//,
  },
  {
    label: "YouTube",
    value: "youtube",
    icon: "/images/icon-youtube.svg",
    placeholder: "e.g. https://youtube.com/@channel",
    bgColor: "#FF0000",
    url: "#",
    validation: /^(https?:\/\/)?(www\.)?(youtube\.com|youtu\.be)\//,
  },
  {
    label: "LinkedIn",
    value: "linkedin",
    icon: "/images/icon-linkedin.svg",
    placeholder: "e.g. https://linkedin.com/in/username",
    bgColor: "#0A66C2",
    url: "#",
    validation: /^(https?:\/\/)?(www\.)?linkedin\.com\/in\//,
  },
  {
    label: "Facebook",
    value: "facebook",
    icon: "/images/icon-facebook.svg",
    placeholder: "e.g. https://facebook.com/username",
    bgColor: "#1877F2",
    url: "#",
    validation: /^(https?:\/\/)?(www\.)?facebook\.com\//,
  },
  {
    label: "Frontend Mentor",
    value: "frontend-mentor",
    icon: "/images/icon-frontend-mentor.svg",
    placeholder: "e.g. https://frontendmentor.io/profile/username",
    bgColor: "#F24E1E",
    url: "#",
    validation: /^(https?:\/\/)?(www\.)?frontendmentor\.io\/profile\//,
  },
];
